using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace WindowsFormsApp16
{
    public partial class Form1 : Form
    {
        List<Button> pictureList;                                           //A list of buttons, pictureList.
        Color[] colors = new Color[]                                        //A list of all the possible colors of the buttons.
        {
            Color.Blue,                                                     //Blue.                            
            Color.Green,                                                    //Green.                               
            Color.Purple,                                                   //Purple.                                
            Color.Red,                                                      //Red.                    
            Color.White,                                                    //White.                                
            Color.Yellow                                                    //Yellow.                                            
        };
        Random r;                                                           //A Random-type variable, r.                

        public Form1()
        {
            InitializeComponent();                                          //Initialize Components.                  
            this.r = new Random();                                          //Random-type variable, r loads.                  
        }

        private void button1_Click(object sender, EventArgs e)
        {
            int input_num;                                                  //An int-type variable, input_num.            
            int button_width = 50;                                          //An int-type variable, button_width equals to 50 "pixels".                                         
            int button_height = 50;                                         //An int-type variable, button_height equals to 50 "pixels". 
            int empty_space = 100;                                          //An int-type variable, empty_space represents the empty space down from the start button.
            int btn_num = 60;                                               //An int-type variable, btn_num represents the size of button and the space between two buttons(50 + 10 = 60 pixels).
            int det_num = (this.Width - empty_space) / btn_num * btn_num;   //An int-type variable, det_num determines button's location.
            pictureList = new List<Button>();                               //List of buttons, pictureList.   

            try
            {
                input_num = Convert.ToInt32(this.textBox1.Text);            //Every input in textBox1 converts to 32-bit integer.                   
            }
            catch                                                           //Exception.                   
            {
                return;
            }
    
            for (int i = 0; i < input_num; i++)                             //A for-loop.                
            {
                Button button = new Button();                               //Generates a new button per loop.                                                     
                button.Size = new Size(button_width, button_height);        //Every button's size is determined.                                                
                int x_axis_number = i * btn_num % det_num / btn_num * btn_num;//An int-type variable, x_axis_number responsible for x-axis button's location.                                                               
                int y_axis_number = i * btn_num / det_num * btn_num;        //An int-type variable, y_axis_number responsible for y-axis button's location.                                           
                button.Location = new Point(empty_space + x_axis_number, empty_space + y_axis_number);
                //Button's location is determined by x_axis_number and y_axis_number after empty_space is added respectively.                                                                                                            
                int color_number = r.Next(0, 6);                            //An int-type variable, color_number is a random integer between 0 and 6.                                                 
                button.BackColor = this.colors[color_number];               //The randomly selected number equals to a color from the colors array.                                                
                button.Text = (i + 1).ToString();                           //Button's text is generated by the for-loop.                                       
                button.Click += new EventHandler(this.pictureClick);        //Button's click event handler is the pictureClick void.
                Controls.Add(button);                                       //Form adds new buttons.                    
                pictureList.Add(button);                                    //List of buttons, pictureList adds new button.                                                            
            }
        }

        public void pictureClick(object sender, EventArgs e)
        {
            MessageBox.Show(((Button)sender).Text);                         //A MessageBox appears when the user clicks on a button(picture).                                                                               
        }

        private void Form1_ResizeBegin(object sender, EventArgs e)
        {
            if (pictureList != null)                                        //If the pictureList is not empty.                
            {
                foreach (Button p in this.pictureList)                      //For each button in the pictureList.                
                {
                    Controls.Remove(p);                                     //Removes one button from pictureList.                     
                }
                pictureList.Clear();                                        //Clears the pictureList.         
            }
        }

        private void Form1_ResizeEnd(object sender, EventArgs e)
        {
            if (pictureList != null)                                        //If the pictureList is not empty.  
            {
                button1.PerformClick();                                     //Generates a click event for buttons.
            }
        }
    }
}